const listWordsDefault = [
  { 
    album: 'Nightmare', 
    coverImg: "https://i.ytimg.com/vi_webp/oZ1FpL8NwxE/maxresdefault.webp",
    songs: [
      {title:'Welcome to Dream',
      linkYT:'https://www.youtube.com/watch?v=oZ1FpL8NwxE'},
      {title:'Chase Me',
      linkYT:'https://www.youtube.com/watch?v=zihoyz0u_cs'},
      {title:'Emotion (소원 하나)',
      linkYT:'https://www.youtube.com/watch?v=5ST_EJBhwO4'},
      {title:'Chase Me (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=tGKOjr5qT-c'}]},
    {album:'Fall asleep in the mirror', 
    coverImg: "https://i.ytimg.com/vi_webp/5ymH694tIpc/maxresdefault.webp",
    songs:[
      {title:'My Toys',
      linkYT:'https://www.youtube.com/watch?v=5ymH694tIpc'},
      {title:'GOOD NIGHT',
      linkYT:'https://www.youtube.com/watch?v=Lxfl8LRab_I'},
      {title:'Lullaby',
      linkYT:'https://www.youtube.com/watch?v=rSq1URfEEC8'},
      {title:'Good Night (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=aioZz8RgB8g'}]},
    {album :'Prequel', 
    coverImg: "https://i.ytimg.com/vi_webp/GBZkdSjG_U4/maxresdefault.webp",
    songs:[
      {title:'Before & After',
      linkYT:'https://www.youtube.com/watch?v=GBZkdSjG_U4'},
      {title:'Fly High',
      linkYT:'https://www.youtube.com/watch?v=39yeTdIuKJU'},
      {title:'Wake Up',
      linkYT:'https://www.youtube.com/watch?v=vuYQhvoYXIQ'},
      {title:'Sleep-walking',
      linkYT:'https://www.youtube.com/watch?v=2_GcbZlDnns'},
      {title:'Trust Me',
      linkYT:'https://www.youtube.com/watch?v=aXFPbEdbe9M'},
      {title:'Fly High (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=xOqDyHfypis'}]},
    {album: 'Full Moon', 
    coverImg: "https://i.ytimg.com/vi_webp/pB4fAzDP2Pw/maxresdefault.webp",
    songs:[
      {title:'Full Moon',
      linkYT:'https://www.youtube.com/watch?v=G1ojcRTiu5g'},
      {title:'Full Moon (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=pB4fAzDP2Pw'}]},
    {album: 'Escape the ERA',
    coverImg: "https://i.ytimg.com/vi_webp/3ntGacSpPQc/maxresdefault.webp", 
    songs:[
      {title:'INSIDE – OUTSIDE',
      linkYT:'https://www.youtube.com/watch?v=3ntGacSpPQc'},
      {title:'YOU AND I',
      linkYT:'https://www.youtube.com/watch?v=I5_BQAtwHws'},
      {title:'Mayday',
      linkYT:'https://www.youtube.com/watch?v=3iqEB5LlO2k'},
      {title:'Which a star',
      linkYT:'https://www.youtube.com/watch?v=EhwX3y9Ty20'},
      {title:'Scar',
      linkYT:'https://www.youtube.com/watch?v=jmYCH6p7HPg'},
      {title:'You And I (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=T2E0jbU-kO8'}]},
    {album: 'Alone In The City', 
    coverImg: "https://i.ytimg.com/vi_webp/dIXdQsz46M0/maxresdefault.webp",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=dIXdQsz46M0'},
      {title:'What',
      linkYT:'https://www.youtube.com/watch?v=pN0dkjp1deQ'},
      {title:'Wonderland',
      linkYT:'https://www.youtube.com/watch?v=iITO8xBvcHI'},
      {title:'Trap',
      linkYT:'https://www.youtube.com/watch?v=eoqwlzfyRSY'},
      {title:'July 7th',
      linkYT:'https://www.youtube.com/watch?v=7u7vUzgtUlk'},
      {title:'What (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=gipiiLebk2c'}]},
    {album: 'What (Japanese ver.)', 
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/0/0e/WhatJapaneseRegular.png",
    songs:[
      {title:'What',
      linkYT:'https://www.youtube.com/watch?v=-GwP6BnZt1Y'},
      {title:'Chase Me',
      linkYT:'https://www.youtube.com/watch?v=LPBIO2B6BEI'},
      {title:'I Miss You',
      linkYT:'https://www.youtube.com/watch?v=BaW7i1bTy5E'}]},
    {album: 'Over the Sky', 
    coverImg: "https://i.ytimg.com/vi_webp/t0LDBoU85Hs/maxresdefault.webp",
      songs:[
        {title:'Over the Sky',
        linkYT:'https://www.youtube.com/watch?v=3F2nRTyVPGo'},  
        {title:'Over the Sky (Inst.)',
        linkYT:'https://www.youtube.com/watch?v=t0LDBoU85Hs'}
    ]},
    {album: 'The End of Nightmare', 
    coverImg: "https://i.ytimg.com/vi_webp/47yVPOjwO_0/maxresdefault.webp",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=47yVPOjwO_0'},
      {title:'PIRI',
      linkYT:'https://www.youtube.com/watch?v=Pq_mbTSR-a0'},
      {title:'Diamond',
      linkYT:'https://www.youtube.com/watch?v=54j-ePPQStU'},
      {title:'And there was no one left',
      linkYT:'https://www.youtube.com/watch?v=Nj5RiXNaqzc'},
      {title:'Daydream',
      linkYT:'https://www.youtube.com/watch?v=X1Mte4dHW1s'},
      {title:'PIRI (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=a2NYg8DaF6s'}
    ]},
    {album: 'PIRI (japanese ver.)',
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/f/f5/PIRIJapaneseRegularVersion.jpg",
    songs: [
      {title:'PIRI',
      linkYT:'https://www.youtube.com/watch?v=ZOsu__wtD30'},
      {title:'Good Night (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=EDbvV8tLu5E'},
      {title:'Wonderland (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=s6xu5S-MAOQ'}
    ]},
    {album: 'The Beginning of the End', 
    coverImg: "https://i.ytimg.com/vi_webp/s6xu5S-MAOQ/maxresdefault.webp",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=sZJblBnvy7A'},
      {title:'Breaking Out',
      linkYT:'https://www.youtube.com/watch?v=SHmOpFbFgrM'},
      {title:'My Way',
      linkYT:'https://www.youtube.com/watch?v=hm1dYdDKS9M'},
      {title:'Chase Me (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=LPBIO2B6BEI'},
      {title:'GOOD NIGHT (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=EDbvV8tLu5E'},
      {title:'Wonderland (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=s6xu5S-MAOQ'},
      {title:'PIRI  (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=lUIqjU5603o'},
      {title:'What (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=O8FfqkPvlxE'},
      {title:'I Miss You',
      linkYT:'https://www.youtube.com/watch?v=IWzCsl6dIao'},
      {title:'And There Was No One Left (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=oxLfVoBOhaY'},
      {title:'You And I (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=6B4sh12t48w'},
      {title:'Outro',
      linkYT:'https://www.youtube.com/watch?v=lG2-McUApbA'}
      ]},
    {album: 'Raid of Dream', 
    coverImg: "https://i.ytimg.com/vi_webp/Iqd8--fIPQk/maxresdefault.webp",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=Iqd8--fIPQk'},
      {title:'Deja Vu',
      linkYT:'https://www.youtube.com/watch?v=W761DtH1oRg'},
      {title:'The curse of the Spider',
      linkYT:'https://www.youtube.com/watch?v=9j0xQh20iVs'},
      {title:'Silent Night',
      linkYT:'https://www.youtube.com/watch?v=ovw4Cy-zMiI'},
      {title:'Polaris',
      linkYT:'https://www.youtube.com/watch?v=jG5CwtPDGB8'}]},
    {album: 'Siyeon 1st Digital Single: Paradise',
    coverImg: "https://i.ytimg.com/vi_webp/-8WPwGT_m-Y/maxresdefault.webp",
    songs:[
      {title:'Paradise (Title Track)',
      linkYT:'https://www.youtube.com/watch?v=BuaGs9W6Un8'},
      {title:'Paradise (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=-8WPwGT_m-Y'}
    ]},
    {album: 'The Tree of Language', 
    coverImg: "https://i.ytimg.com/vi_webp/NfeYX7VW7PU/maxresdefault.webp",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=NfeYX7VW7PU'},
      {title:'Scream',
      linkYT:'https://www.youtube.com/watch?v=FKlGHHhTOsQ'},
      {title:'Tension',
      linkYT:'https://www.youtube.com/watch?v=oI6DkAl4LSs'},
      {title:'Red Sun',
      linkYT:'https://www.youtube.com/watch?v=RKBJVdjOHUY'},
      {title:'Black Or White',
      linkYT:'https://www.youtube.com/watch?v=t3ptx0spMtQ'},
      {title:'Jazz Bar',
      linkYT:'https://www.youtube.com/watch?v=Fo64mNT5GOA'},
      {title:'SAHARA',
      linkYT:'https://www.youtube.com/watch?v=BgLhbkKu1s4'},
      {title:'In The Frozen',
      linkYT:'https://www.youtube.com/watch?v=okGlx-t9hXA'},
      {title:'Daybreak',
      linkYT:'https://www.youtube.com/watch?v=Um2tn8zM8bM'},
      {title:'Full Moon',
      linkYT:'https://www.youtube.com/watch?v=G1ojcRTiu5g'},
      {title:'Over the Sky',
      linkYT:'https://www.youtube.com/watch?v=3F2nRTyVPGo'},
      {title:'Outro',
      linkYT:'https://www.youtube.com/watch?v=D0SmrLNv45M'},
      {title:'Scream(inst)',
      linkYT:'https://www.youtube.com/watch?v=mdBosrGac_A'},
      {title:'Paradise',
      linkYT:'https://www.youtube.com/watch?v=6TyOvuMWGSQ'}
    ]},
    {album: 'Endless Night', 
    coverImg: "https://i.ytimg.com/vi_webp/Om4xNQhHI6k/maxresdefault.webp",
    songs:[
      {title:'Endless Night',
      linkYT:'https://www.youtube.com/watch?v=wCALuFy2YVI'},
      {title:'Over The Sky (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=Om4xNQhHI6k'},
      {title:'Silent Night (Japanese Version)',
      linkYT:'https://www.youtube.com/watch?v=aH6VcimxcuI'}]},
    {album: 'R.o.S.E BLUE', 
    coverImg: "https://i.ytimg.com/vi_webp/Gu_hIDh0HIw/maxresdefault.webp",
    songs:[
      {title:'R.o.S.E BLUE',
      linkYT:'https://www.youtube.com/watch?v=Lja79dlQiZI'}, 
      {title:'R.o.S.E BLUE (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=Xk4YmmYjlUU'}]},
    {album: 'Lose Myself', 
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/d/dc/Dystopia_Lose_Myself_Digital_Cover.jpg",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=DW6pUU4TFj8'},
      {title:'BOCA',
      linkYT:'https://www.youtube.com/watch?v=MZ4JGye4dQU'},
      {title:'Break The Wall',
      linkYT:'https://www.youtube.com/watch?v=F_2W8SW8iXA'},
      {title:'Can\'t get you out of my mind',
      linkYT:'https://www.youtube.com/watch?v=F_2W8SW8iXA'},
      {title:'Dear',
      linkYT:'https://www.youtube.com/watch?v=nqrHHZjc_Rs'},
      {title:'BOCA (Inst.)',
      linkYT:'https://www.youtube.com/watch?v=wBr8gB-0WJA'}
    ]}, 
    {album: 'Handong 1st Digital Single: First Light of Dawn',
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/c/c0/First_Lights_of_Dawn_Digital_Cover.jpg",
    songs:[{title:'First Light of Dawn',
    linkYT:'https://www.youtube.com/watch?v=jmwgJLfkJ7Y'}]},
    {album: 'JP Single: no more',
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/8/8b/Dreamcatcher_No_More.jpg",
    songs:[
      {title:'No More',
      linkYT:'https://www.youtube.com/watch?v=HanFwe41w9s'}
    ]},
    {album:'Successors of the Will Anime OP',
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/d/d8/Eclipse_%28TV_size%29_Album_Cover.jpg",
    songs:[{title:'Eclipse',
    linkYT:'https://www.youtube.com/watch?v=mU2ok2aTeFk'}]},
    {album: 'Dystopia: Road to Utopia', 
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/e/e6/Dystopia_Road_to_Utopia_digital_album_cover.jpg",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=0KAPMuPWktg'},
      {title:'Odd Eye',
      linkYT:'https://www.youtube.com/watch?v=1QD0FeZyDtQ'},
      {title:'Wind Blows',
      linkYT:'https://www.youtube.com/watch?v=w8rCz3gSuH0'},
      {title:'Poison Love',
      linkYT:'https://www.youtube.com/watch?v=RwOO-BONYQg'},
      {title:'4 Memory',
      linkYT:'https://www.youtube.com/watch?v=SGemMpImsXg'},
      {title:'New Days',
      linkYT:'https://www.youtube.com/watch?v=Ag2AWsFY5Ns'},
      {title:'Odd Eye (Inst.)',
      linkYT:'https://youtu.be/PPDsgFOFVxA'}
    ]},
    {album: 'Eclipse', 
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/7/7d/Eclipse_Regular_cover.png",
    songs:[
      {title:'Eclipse',
      linkYT:'https://www.youtube.com/watch?v=b9UxVkTfkVg'},
      {title:'No More',
      linkYT:'https://www.youtube.com/watch?v=HanFwe41w9s'},
      {title:'Don\'t Light My Fire',
      linkYT:'https://www.youtube.com/watch?v=_r2LYookCz8'},
      {title:'Eclipse (Inst)',
      linkYT:'https://www.youtube.com/watch?v=QFCUrLImALk'},
      {title:'No More (Inst)',
      linkYT:'https://www.youtube.com/watch?v=CWEZN1hXf54'},
      {title:'Don\'t Light My Fire (Inst)',
      linkYT:'https://www.youtube.com/watch?v=ox37s4ttyYQ'}]},
    {album: 'Summer Holiday', 
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/2/28/Dreamcatcher_Summer_Holiday_album_cover.jpg",
    songs:[
      {title:'Intro',
      linkYT:'https://www.youtube.com/watch?v=Z-ig0ZAbdk0'},
      {title:'BEcause',
      linkYT:'https://www.youtube.com/watch?v=PEKkdIT8JPM'},
      {title:'Airplane',
      linkYT:'https://www.youtube.com/watch?v=sNgM3uBLkEU'},
      {title:'Whistle',
      linkYT:'https://www.youtube.com/watch?v=KLozldjxyu4'},
      {title:'Alldaylong',
      linkYT:'https://www.youtube.com/watch?v=AWemTDbxs14'},
      {title:'A Heart of Sunflower',
      linkYT:'https://www.youtube.com/watch?v=5gvfp-haKXc'}]},
    {album: 'Apocalypse: Save Us', 
    coverImg: "https://static.wikia.nocookie.net/dreamcatcherwiki/images/2/2c/Dreamcatcher_Apocalypse_Save_Us_album_cover.jpg",
    songs:[
      {title:'Save Us',
      linkYT:'https://www.youtube.com/watch?v=oB-War_KaAQ'},
      {title:'Locked Inside A Door',
      linkYT:'https://www.youtube.com/watch?v=jZgfRnnKhlA'},
      {title:'Maison',
      linkYT:'https://www.youtube.com/watch?v=z4t9LLq1Nk0'},
      {title:'Starlight',
      linkYT:'https://www.youtube.com/watch?v=chYPWJk6s6E'},
      {title:'Together',
      linkYT:'https://www.youtube.com/watch?v=FFXtTiikOic'},
      {title:'널 위해 (Always)',
      linkYT:'https://www.youtube.com/watch?v=KhdZcg481x4'},
      {title:'Skit: The seven doors',
      linkYT:'https://www.youtube.com/watch?v=7Q5hqB9yTzE'},
      {title:'Cherry(Real Miracle)',
      linkYT:'https://www.youtube.com/watch?v=2L0q-nWS1xA'},
      {title:'No Dot',
      linkYT:'https://www.youtube.com/watch?v=oxPyRRKEtHI'},
      {title:'황홀경 (极夜) (Entrancing)',
      linkYT:'https://www.youtube.com/watch?v=CowRTDlxbWg'},
      {title:'한겨울 (寒冬) (Winter)',
      linkYT:'https://www.youtube.com/watch?v=jQ_ogJWssXU'},
      {title:'For',
      linkYT:'https://www.youtube.com/watch?v=1HwjxbE7_Qw'},
      {title:'Beauty Full',
      linkYT:'https://www.youtube.com/watch?v=nivI7w9HagI'},
      {title:'Playground',
      linkYT:'https://www.youtube.com/watch?v=iYvErpLnQ-8'}
      ]}, 
    {album: 'Vision', 
    coverImg: "https://yt3.ggpht.com/jsT91joeT19uOyTR6L9Rt4BBpWEVWAWQPndVz2iNxHkMGl23IT_PvOA3Vn8uu7PYyMxQaqfH",
    songs:[
      {title:'Chaotical X',
      linkYT:''}, 
      {title:'Vision',
      linkYT:''},
      {title:'Fairytale',
      linkYT:''},
      {title:'Some love',
      linkYT:''},
      {title:'이 비가 그칠 때면(Rainy day)',
      linkYT:''},
      {title:'Mother nature',
      linkYT:''}
    ]}
];

export default listWordsDefault;